### ISSUE TITLE
so files were loss?

### ISSUE THREAD

**Issue by xzhluo** [goldfish07/ResChiper#5]
this is app-release.aab
![1703060944915_846075D0-DFD1-4f80-BBFF-E6BCF22D06F8](https://github.com/goldfish07/ResChiper/assets/25238273/badf47ff-25b5-4b5c-8ec4-16e6fc5465ca)

this is reschiper-app.aab
![1703058105671_8C35723E-0E23-4564-B1EB-87662DA57955](https://github.com/goldfish07/ResChiper/assets/25238273/35f2680b-03d4-4eed-b66f-067a90f9b34e)

lib dir was dismiss

build.gradle is defult config

**Comment by goldfish07** [comment]
comment out abi in fileFilterList

    fileFilterList = [ // file filter rules
//                       "*/armeabi-v7a/*",
//                       "*/arm64-v8a/*",
//                       "*/x86/*",
//                       "*/x86_64/*",
                       "META-INF/*"
    ]

**Comment by xzhluo** [comment]
> When utilizing a fileFilterList, files within the directories specified in the list are excluded from the app bundle.
> 
> comment out abi dir in fileFilterList
> 
> ```
>     fileFilterList = [ // file filter rules
> //                       "*/armeabi-v7a/*",
> //                       "*/arm64-v8a/*",
> //                       "*/x86/*",
> //                       "*/x86_64/*",
>                        "META-INF/*"
>     ]
> ```

thanks， i resolved the issue。fileFileterList is useless
![image](https://github.com/goldfish07/ResChiper/assets/25238273/c1bf8a6f-5687-46cd-84de-c70a15c302ac)

**Comment by goldfish07** [comment]
Good to hear you resolved issue your own :)

fileFilterList becomes particularly useful when a library includes unnecessary files that are not used or required by your app in the final app bundle. When used correctly,

fileFilterList is instrumental in reducing the app bundle size, ensuring that only essential files are included. This optimization is crucial for improving download and installation times, enhancing performance, and minimizing storage space requirements in Android device.

**Comment by xzhluo** [comment]
> Good to hear you resolved issue your own :)
> 
> fileFilterList becomes particularly useful when a library includes unnecessary files that are not used or required by your app in the final app bundle. When used correctly,
> 
> fileFilterList is instrumental in reducing the app bundle size, ensuring that only essential files are included. This optimization is crucial for improving download and installation times, enhancing performance, and minimizing storage space requirements in Android device.

Got it, thanks you again.
